### ISSUE TITLE
Read `ECMAScript 2015 - Let’s talk about ES6`

### ISSUE THREAD

**Issue by arrowrowe** [arrowrowe/es6-playground#1]
Last updated: 2015-06-21 01:13

[ECMAScript 2015 - Let’s talk about ES6](https://medium.com/ecmascript-2015)
- [x] [0. Let's talk about ECMAScript 2015](https://medium.com/ecmascript-2015/let-s-talk-about-javascript-ecmascript-2015-es6-say-hello-world-658ce6941c)
- [x] [1. Let and const](https://medium.com/ecmascript-2015/let-const-35bca3b4a3c6)
- [x] [2. Arrow functions](https://medium.com/ecmascript-2015/arrow-functions-bb08eeb11667)
- [x] [3. Default, rest, spread](https://medium.com/ecmascript-2015/default-rest-spread-f3ab0d2e0a5e)
- [x] [4. Destructuring](https://medium.com/ecmascript-2015/es6-destructuring-13ca399f993a)
- [x] [5. Strings](https://medium.com/ecmascript-2015/es6-string-bae03d964d43)
- [x] [6. Iterators](https://medium.com/ecmascript-2015/es6-iterators-4afec026f70a)
- [x] [7. Generators](https://medium.com/ecmascript-2015/es6-generators-4494aa135ad3)
- [x] [8. Classes and Inheritance](https://medium.com/ecmascript-2015/es6-classes-and-inheritance-607804080906)
- [x] [9. Modules](https://medium.com/ecmascript-2015/es6-modules-d5646d1b9a08)
- [x] [10. Promises](https://medium.com/ecmascript-2015/es6-promises-9ca8d8b4aca6)
- [x] [11. Set, map, weak](https://medium.com/ecmascript-2015/es6-set-map-weak-a2aeb7e2d384)

_- fin -_

**Comment by at15** [comment]
lets prepare for the final exam....

**Comment by arrowrowe** [comment]
re @at15: Life goes on without gpa...

**Comment by at15** [comment]
@arrowrowe  you can't go abroad if you don't match 3.0, you got 3.5+ you may save 50w+....

**Comment by arrowrowe** [comment]
Haven't figured out a good sample for Chapter 8. Don't like vehicle and car etc...

**Comment by at15** [comment]
@arrowrowe try :sheep: and Mie.

**Comment by arrowrowe** [comment]
Don't like the module idea in Chapter 9. Seems too far away from the familiar JavaScript taste.

**Comment by at15** [comment]
@arrowrowe someone said the class in es6 would disable mixin in react, and need es7's decorator

**Comment by arrowrowe** [comment]
Re @at15: yep. Like getter/setter, but other sugar...... Maybe just don't want to move on.

**Comment by arrowrowe** [comment]
Seems no need to write a sample for Chapter 11.

_- fin -_
