### ISSUE TITLE
Extract resource from `18 Resources on ES6 for JavaScript Developers`

### ISSUE THREAD

**Issue by arrowrowe** [arrowrowe/es6-playground#3]
Last update: 2015-06-22 22:22.

[18 Resources on ES6 for JavaScript Developers](http://codecondo.com/learn-ecmascript-6-resources-javascript-devs/)
- [ ] 0. [②ality](http://www.2ality.com/)
- [ ] 1. [ES Discuss](https://esdiscuss.org/)
- [x] 2. [ES6 In Depth Articles](https://hacks.mozilla.org/category/es6-in-depth/): See #5.
- [ ] 3. [ES6 Interactive Guide](http://projects.formidablelabs.com/es6-interactive-guide/#/)
- [ ] 4. [ECMAscript 6 Lessons](https://egghead.io/technologies/es6)
- [ ] 5. [ECMAScript 6 Compatibility](http://kangax.github.io/compat-table/es6/)
- [ ] 6. [Learn ES2015](https://babeljs.io/docs/learn-es2015/)
- [ ] 7. [ES6 Katas](http://es6katas.org/)
- [ ] 8. [JavaScript Fundamentals for ES6](http://www.pluralsight.com/courses/javascript-fundamentals-es6)
- [ ] 9. [Learn Harmony](http://learnharmony.org/#)
- [ ] 10. [ES6 Fiddle](http://www.es6fiddle.net/)
- [ ] 11. [Exploring ES6](http://exploringjs.com/)
- [ ] 12. [Understanding ECMAScript 6](https://leanpub.com/understandinges6)
- [ ] 13. [You Don’t Know JS: ES6 & Beyond](http://shop.oreilly.com/product/0636920033769.do)
- [ ] 14. [JavaScript Allongé, the “Six” Edition](https://leanpub.com/javascriptallongesix)
- [x] 15. [ECMAScript 2015](https://medium.com/ecmascript-2015): See #1.
- [ ] 16. [Things You Need To Know About ECMAScript 6](https://medium.com/@victorleungtw/12-things-you-need-to-know-about-ecmascript-6-31ae1589e47c)
- [ ] 17. [A Smooth Transition to ECMAScript 6](https://blog.engineyard.com/2015/smooth-transition-ecmascript-6-integration)

_- fin -_

**Comment by arrowrowe** [comment]
Begin to prepare for the next final today... I'll be back...

**Comment by at15** [comment]
good night mie

**Comment by arrowrowe** [comment]
Close due to TLE.
